/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.tests;

import com.google.inject.Inject;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.asmetal.asmetaL.Asm;

/* @RunWith(/* name is null */)
@InjectWith(AsmetaLInjectorProvider.class) */@SuppressWarnings("all")
public class AsmetaLParsingTest {
  @Inject
  private /* ParseHelper<Asm> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field AsmetaLParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\njoin cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
