/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.web;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class AsmetaLWebModule extends AbstractAsmetaLWebModule {
}
