/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AsmetaLValidator extends AbstractAsmetaLValidator {
}
