/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AsmetaLIdeModule extends AbstractAsmetaLIdeModule {
}
