/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.asmetal.AsmetaLRuntimeModule;
import org.xtext.asmetal.AsmetaLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AsmetaLIdeSetup extends AsmetaLStandaloneSetup {
  @Override
  public Injector createInjector() {
    AsmetaLRuntimeModule _asmetaLRuntimeModule = new AsmetaLRuntimeModule();
    AsmetaLIdeModule _asmetaLIdeModule = new AsmetaLIdeModule();
    return Guice.createInjector(Modules2.mixin(_asmetaLRuntimeModule, _asmetaLIdeModule));
  }
}
